### PR TITLE
Fix #16

### LINKED ISSUE #16: handling of for loops doesn't correctly take breaks into account
The following code compiles without errors:

``` rust
#![feature(plugin)]
#![feature(custom_attribute)]
#![plugin(humpty_dumpty)]
#![allow(unused_attributes)]
#![allow(unused_variables)]
#![allow(dead_code)]

#[drop_protect]
struct Foo;

impl Foo {
    #[allow_drop="Foo"]
    fn close(self) { }
}

fn test1() {
    let f = vec!(Foo); //~ ERROR dropped
    for i in f {
        if true {
            break;
        }
        i.close();
    }
}

fn main() {}
```

It really shouldn't.

### PR DESCRIPTION
**Pull request by Munksgaard**
I made a mess with this one, we probably need to merge #13 first.

### CODE REVIEW

**Comment by Munksgaard** [comment]
It's supposed to fix #16

**Comment by Manishearth** [comment]
\o/

**Comment by Munksgaard** [comment]
Sorry for the spam...

**Comment by Manishearth** [comment]
Retroactive review: LGTM :)

**Pull request merged**
